name       : perl-lingua-translit
version    : 0.27
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/A/AL/ALINKE/Lingua-Translit-0.27.tar.gz : 650f40c06342d112b53450a8eeba942074af333af39f24d20654e65596530d2c
license    : Artisitic-1.0-Perl
component  : programming.perl
summary    : Lingua::Translit - transliterates text between writing systems
description: |
    Lingua::Translit can be used to convert text from one writing system to another, based on national or international transliteration tables. Where possible a reverse transliteration is supported.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
