name       : perl-lingua-translit
version    : '0.28'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/A/AL/ALINKE/Lingua-Translit-0.28.tar.gz : 113f91d8fc2c630437153a49fb7a52b023af8f6278ed96c070b1f60824b8eae1
license    : Artisitic-1.0-Perl
component  : programming.perl
summary    : Lingua::Translit - transliterates text between writing systems
description: |
    Lingua::Translit can be used to convert text from one writing system to another, based on national or international transliteration tables. Where possible a reverse transliteration is supported.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
